### ISSUE TITLE
[APP BUG]: Unknown game entry on grid view that crashes the app, can crash the os if deleted

### ISSUE THREAD

**Issue by mAmineChniti** [shadps4-emu/shadPS4#2242]
### Checklist

- [x] I have searched for a similar issue in this repository and did not find one.
- [x] I am using an official build obtained from [releases](https://github.com/shadps4-emu/shadPS4/releases) or updated one of those builds using its in-app updater.

### Describe the Bug

there's an imageless game entry when you select grid view, it crashes the app when you have it selected and change game list icons size, if you delete that game entry it deletes everything in ~/
i'm using the official flatpak

### Reproduction Steps

![Image](https://github.com/user-attachments/assets/acaa8c7b-e6b3-4798-8509-abdd874af374)

- Game list mode -> grid view
- select the imageless nameless game entry
- change the game list icons size, or delete that game entry

### Specify OS Version

Debian 12

**Comment by roamic** [comment]
Can you attach `config.toml` from the shadPS4 user directory? Also, what's the contents of shadPS4 games directory?

**Comment by mAmineChniti** [comment]
i'm not sure how to access the config.toml, this is the flatpak version btw, and the games dir only has that deadpool game only

**Comment by mAmineChniti** [comment]
```toml
[General]
logType = "async"
separateUpdateEnabled = false
showSplash = false
Fullscreen = false
checkCompatibilityOnStartup = false
updateChannel = "Release"
logFilter = ""
enableDiscordRPC = false
compatibilityEnabled = true
autoUpdate = false
userName = "shadPS4"
isTrophyPopupDisabled = false
playBGM = false
isPS4Pro = true
BGMvolume = 50

[Input]
cursorState = 1
cursorHideTimeout = 5
backButtonBehavior = "left"
specialPadClass = 1
useSpecialPad = false

[GPU]
screenWidth = 1280
screenHeight = 720
nullGpu = false
copyGPUBuffers = false
vblankDivider = 1
dumpShaders = false
patchShaders = true

[Vulkan]
gpuId = 1
validation = false
rdocMarkersEnable = false
validation_sync = false
validation_gpu = false
rdocEnable = false
crashDiagnostic = false

[Debug]
DebugDump = false
CollectShader = false

[GUI]
geometry_y = 36
sliderPosGrid = 0
geometry_w = 1920
mw_width = 1920
gameTableMode = 0
theme = 0
recentFiles = []
pkgDirs = []
addonInstallDir = "/home/amine/.var/app/net.shadps4.shadPS4/data/shadPS4/addcont"
geometry_h = 996
mw_height = 996
elfDirs = []
iconSizeGrid = 69
installDirs = ["/home/amine/PS4"]
sliderPos = 0
iconSize = 36
emulatorLanguage = "en"
geometry_x = 0

[Settings]
consoleLanguage = 1
```
