### ISSUE TITLE
[SUGGESTION] Build as Flatpak

### ISSUE THREAD

**Issue by Captn138** [shadps4-emu/shadPS4#272]
Building as a Flatpak would be great for Linux users.
Also, it would normalize the behavior on lal devices and facilitate installation on steam deck.

**Comment by Caua77** [comment]
Most emulators are already in flathub, so it will be very welcome to his entrance too.

**Comment by Hermiten** [comment]
Any news about this ? Maybe someone can work on it ?

**Comment by deadmeu** [comment]
I've been working on a manifest for a bit but can't quite get it working. Maybe someone else can finish it off:
```yml
app-id: com.shadps4.Emulator
runtime: org.freedesktop.Platform
runtime-version: '23.08'
sdk: org.freedesktop.Sdk
command: shadps4
finish-args:
  - --share=network
  - --socket=pulseaudio
  - --socket=wayland
  - --socket=x11
  - --device=dri
  - --filesystem=home

modules:
  - name: libevdev
    buildsystem: meson
    config-opts:
      - -Dtests=disabled
      - -Ddocumentation=disabled
    # cleanup:
    #   - /bin
    #   - /include
    #   - /lib/pkgconfig
    #   - /share
    sources:
      - type: archive
        url: https://www.freedesktop.org/software/libevdev/libevdev-1.13.3.tar.xz
        sha256: abf1aace86208eebdd5d3550ffded4c8d73bb405b796d51c389c9d0604cbcfbf
        x-checker-data:
          type: anitya
          project-id: 20540
          stable-only: true
          url-template: https://www.freedesktop.org/software/libevdev/libevdev-$version.tar.xz

  - name: shadPS4
    buildsystem: cmake
    builddir: true
    config-opts:
      - -DCMAKE_BUILD_TYPE=Release
      # - -DENABLE_QT_GUI=ON
    build-options:
      env:
        CMAKE_C_COMPILER: clang
        CMAKE_CXX_COMPILER: clang++
    sources:
      # - type: git
      #   url: https://github.com/shadps4-emu/shadPS4.git
      #   branch: main
      - type: dir
        path: .
```
